-- MySQL Script generated by MySQL Workbench
-- Mon Ven 20 18:52:26 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

DROP SCHEMA IF EXISTS `tifosi` ;
CREATE SCHEMA IF NOT EXISTS `tifosi` DEFAULT CHARACTER SET 'utf8' ;
USE `tifosi` ;


-- ============================
-- Table : boisson
-- ============================
CREATE TABLE boisson (
    id_boisson INT PRIMARY KEY,
    nom_boisson VARCHAR(50) NOT NULL,
    id_marque INT NOT NULL,
    CONSTRAINT fk_boisson_marque
      FOREIGN KEY (`id_marque`)
      REFERENCES `tifosi`.`marque` (`id_marque`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION);

-- ============================
-- Table : marque
-- ============================
CREATE TABLE marque (
    id_marque INT PRIMARY KEY,
    nom_marque VARCHAR(50) NOT NULL UNIQUE,
  PRIMARY KEY (`id_marque`)
  );

-- ============================
-- Table : ingredient
-- ============================
CREATE TABLE ingredient (
    id_ingredient INT PRIMARY KEY,
    nom_ingredient VARCHAR(50) NOT NULL UNIQUE
);

-- ============================
-- Table : menu
-- ============================
CREATE TABLE menu (
    id_menu INT PRIMARY KEY,
    prix DECIMAL(5,2) NOT NULL CHECK (prix > 0)
);

-- ============================
-- Table : focaccia
-- ============================
CREATE TABLE focaccia (
    id_focaccia INT PRIMARY KEY,
    nom_focaccia VARCHAR(50) NOT NULL UNIQUE,
    prix DECIMAL(5,2) NOT NULL CHECK (prix > 0),
    id_menu INT NULL,
    CONSTRAINT fk_focaccia_menu
      FOREIGN KEY (id_menu)
      REFERENCES menu(id_menu)
);

-- ============================
-- Table : client
-- ============================
CREATE TABLE client (
    id_client INT PRIMARY KEY,
    nom VARCHAR(50) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    code_postal INT NOT NULL
);


-- ============================
-- Table : menu_boisson
-- ============================
CREATE TABLE menu_boisson (
    id_menu INT NOT NULL,
    id_boisson INT NOT NULL,
    PRIMARY KEY (id_menu, id_boisson),
    CONSTRAINT fk_mb_menu
        FOREIGN KEY (id_menu) REFERENCES menu(id_menu)
            ON DELETE CASCADE,
    CONSTRAINT fk_mb_boisson
        FOREIGN KEY (id_boisson) REFERENCES boisson(id_boisson)
            ON DELETE CASCADE
);


-- ============================
-- Table : focaccia_ingredient
-- ============================
CREATE TABLE focaccia_ingredient (
    id_focaccia INT NOT NULL,
    id_ingredient INT NOT NULL,
    quantite INT NOT NULL CHECK (quantite > 0),
    PRIMARY KEY (id_focaccia, id_ingredient),
    CONSTRAINT fk_fi_focaccia
        FOREIGN KEY (id_focaccia) REFERENCES focaccia(id_focaccia)
            ON DELETE CASCADE,
    CONSTRAINT fk_fi_ingredient
        FOREIGN KEY (id_ingredient) REFERENCES ingredient(id_ingredient)
            ON DELETE CASCADE
);


-- ============================
-- Table : client_menu
-- ============================
CREATE TABLE client_menu (
    id_client INT NOT NULL,
    id_menu INT NOT NULL,
    date_achat DATE NOT NULL,
    PRIMARY KEY (id_client, id_menu, date_achat),
    CONSTRAINT fk_cm_client
        FOREIGN KEY (id_client) REFERENCES client(id_client)
            ON DELETE CASCADE,
    CONSTRAINT fk_cm_menu
        FOREIGN KEY (id_menu) REFERENCES menu(id_menu)
            ON DELETE CASCADE
);

SET SQL_MODE = '';
DROP USER IF EXISTS tifosiUser@localhost;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'tifosiUser'@'localhost' IDENTIFIED BY 'TifosiPassword13!!';

GRANT ALL PRIVILEGES  ON tifosiUser.* TO 'tifosiUser'@'localhost';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
